list(APPEND adcirc_src_files
  ADCIRC/src/sizes.F
  ADCIRC/thirdparty/KDTREE2/kdtree2.F
  ADCIRC/src/global.F
  ADCIRC/src/boundaries.F
  ADCIRC/src/mesh.F
  ADCIRC/src/vew1d.F
  ADCIRC/src/global_3dvs.F
  ADCIRC/src/harm.F
  ADCIRC/wind/vortex.F
  ADCIRC/src/wind.F
  ADCIRC/src/owiwind.F
  ADCIRC/src/owiwind_netcdf.F
  ADCIRC/src/rs2.F
  ADCIRC/src/owi_ice.F
  ADCIRC/src/itpackv.F
  ADCIRC/src/nodalattr.F
  ADCIRC/src/globalio.F
  ADCIRC/src/subdomain.F
  ADCIRC/src/gwce.F
  ADCIRC/src/wetdry.F
  ADCIRC/src/momentum.F
  ADCIRC/src/netcdfio.F
  ADCIRC/src/control.F
  ADCIRC/src/xdmfio.F
  ADCIRC/src/hashtable.F
  ADCIRC/src/write_output.F
  ADCIRC/src/couple2swan.F
  ADCIRC/src/adcirc.F
  ADCIRC/src/weir_boundary.F
  ADCIRC/src/read_input.F
  ADCIRC/src/cstart.F
  ADCIRC/src/hstart.F
  ADCIRC/src/timestep.F
  ADCIRC/src/vsmy.F
  ADCIRC/src/transport.F
  ADCIRC/src/driver.F
  ADCIRC/src/sponge_layer.F
  ADCIRC/src/quadrature.F
  ADCIRC/src/couple2baroclinic3D.F)

list(APPEND adcprep_src_files
  ADCIRC/src/sizes.F
  ADCIRC/thirdparty/KDTREE2/kdtree2.F
  ADCIRC/src/global.F
  ADCIRC/src/boundaries.F
  ADCIRC/src/hashtable.F
  ADCIRC/src/mesh.F
  ADCIRC/src/vew1d.F
  ADCIRC/src/global_3dvs.F
  ADCIRC/wind/vortex.F
  ADCIRC/src/owiwind.F
  ADCIRC/src/owiwind_netcdf.F
  ADCIRC/src/rs2.F
  ADCIRC/src/owi_ice.F
  ADCIRC/src/wind.F
  ADCIRC/prep/presizes.F
  ADCIRC/prep/pre_global.F
  ADCIRC/prep/metis.F
  ADCIRC/prep/subprep.F
  ADCIRC/prep/adcprep.F
  ADCIRC/prep/decomp.F
  ADCIRC/prep/prep_weir.F
  ADCIRC/src/itpackv.F
  ADCIRC/src/nodalattr.F
  ADCIRC/src/harm.F
  ADCIRC/prep/read_global.F
  ADCIRC/src/subdomain.F
  ADCIRC/src/gwce.F
  ADCIRC/src/wetdry.F
  ADCIRC/src/momentum.F
  ADCIRC/src/netcdfio.F
  ADCIRC/prep/prep.F
  ADCIRC/prep/interp.F
  ADCIRC/prep/machdep.F
  ADCIRC/src/sponge_layer.F
  ADCIRC/src/quadrature.F
  ADCIRC/src/couple2baroclinic3D.F)
