list(APPEND adcirc_src_files
  ADCIRC/src/sizes.F
  ADCIRC/thirdparty/KDTREE2/kdtree2.F
  ADCIRC/src/global.F
  ADCIRC/src/boundaries.F
  ADCIRC/src/mesh.F
  ADCIRC/src/vew1d.F
  ADCIRC/src/global_3dvs.F
  ADCIRC/src/harm.F
  ADCIRC/wind/vortex.F
  ADCIRC/src/wind.F
  ADCIRC/src/owiwind.F
  ADCIRC/src/owiwind_netcdf.F
  ADCIRC/src/rs2.F
  ADCIRC/src/owi_ice.F
  ADCIRC/src/itpackv.F
  ADCIRC/src/nodalattr.F
  ADCIRC/src/globalio.F
  ADCIRC/src/subdomain.F
  ADCIRC/src/gwce.F
  ADCIRC/src/wetdry.F
  ADCIRC/src/momentum.F
  ADCIRC/src/netcdfio.F
  ADCIRC/src/control.F
  ADCIRC/src/xdmfio.F
  ADCIRC/src/hashtable.F
  ADCIRC/src/write_output.F
  ADCIRC/src/couple2swan.F
  ADCIRC/src/adcirc.F
  ADCIRC/src/weir_boundary.F
  ADCIRC/src/read_input.F
  ADCIRC/src/cstart.F
  ADCIRC/src/hstart.F
  ADCIRC/src/timestep.F
  ADCIRC/src/vsmy.F
  ADCIRC/src/transport.F
  ADCIRC/src/driver.F
  ADCIRC/src/sponge_layer.F
  ADCIRC/src/quadrature.F
  ADCIRC/src/couple2baroclinic3D.F)

list(APPEND adcprep_src_files
  ADCIRC/src/sizes.F
  ADCIRC/thirdparty/KDTREE2/kdtree2.F
  ADCIRC/src/global.F
  ADCIRC/src/boundaries.F
  ADCIRC/src/hashtable.F
  ADCIRC/src/mesh.F
  ADCIRC/src/vew1d.F
  ADCIRC/src/global_3dvs.F
  ADCIRC/wind/vortex.F
  ADCIRC/src/owiwind.F
  ADCIRC/src/owiwind_netcdf.F
  ADCIRC/src/rs2.F
  ADCIRC/src/owi_ice.F
  ADCIRC/src/wind.F
  ADCIRC/prep/presizes.F
  ADCIRC/prep/pre_global.F
  ADCIRC/prep/metis.F
  ADCIRC/prep/subprep.F
  ADCIRC/prep/adcprep.F
  ADCIRC/prep/decomp.F
  ADCIRC/prep/prep_weir.F
  ADCIRC/src/itpackv.F
  ADCIRC/src/nodalattr.F
  ADCIRC/src/harm.F
  ADCIRC/prep/read_global.F
  ADCIRC/src/subdomain.F
  ADCIRC/src/gwce.F
  ADCIRC/src/wetdry.F
  ADCIRC/src/momentum.F
  ADCIRC/src/netcdfio.F
  ADCIRC/prep/prep.F
  ADCIRC/prep/interp.F
  ADCIRC/prep/machdep.F
  ADCIRC/src/sponge_layer.F
  ADCIRC/src/quadrature.F
  ADCIRC/src/couple2baroclinic3D.F)

list(APPEND util_src_files
  ADCIRC/util/adccmp.F
  ADCIRC/wind/p15.F
  ADCIRC/wind/owi22.F
  ADCIRC/util/build13.F
  ADCIRC/util/buildstwave23.F
  ADCIRC/util/hot2asc.F
  ADCIRC/util/inflate.F
  ADCIRC/util/hstime.F
  ADCIRC/util/adcircResultsComparison.F90)

list(APPEND metis_src_files
  ADCIRC/thirdparty/metis/Lib/coarsen.c
  ADCIRC/thirdparty/metis/Lib/fm.c
  ADCIRC/thirdparty/metis/Lib/initpart.c
  ADCIRC/thirdparty/metis/Lib/match.c
  ADCIRC/thirdparty/metis/Lib/ccgraph.c
  ADCIRC/thirdparty/metis/Lib/memory.c
  ADCIRC/thirdparty/metis/Lib/pmetis.c
  ADCIRC/thirdparty/metis/Lib/pqueue.c
  ADCIRC/thirdparty/metis/Lib/refine.c
  ADCIRC/thirdparty/metis/Lib/util.c
  ADCIRC/thirdparty/metis/Lib/timing.c
  ADCIRC/thirdparty/metis/Lib/debug.c
  ADCIRC/thirdparty/metis/Lib/bucketsort.c
  ADCIRC/thirdparty/metis/Lib/graph.c
  ADCIRC/thirdparty/metis/Lib/stat.c
  ADCIRC/thirdparty/metis/Lib/kmetis.c
  ADCIRC/thirdparty/metis/Lib/kwayrefine.c
  ADCIRC/thirdparty/metis/Lib/kwayfm.c
  ADCIRC/thirdparty/metis/Lib/balance.c
  ADCIRC/thirdparty/metis/Lib/ometis.c
  ADCIRC/thirdparty/metis/Lib/srefine.c
  ADCIRC/thirdparty/metis/Lib/sfm.c
  ADCIRC/thirdparty/metis/Lib/separator.c
  ADCIRC/thirdparty/metis/Lib/mincover.c
  ADCIRC/thirdparty/metis/Lib/mmd.c
  ADCIRC/thirdparty/metis/Lib/mesh.c
  ADCIRC/thirdparty/metis/Lib/meshpart.c
  ADCIRC/thirdparty/metis/Lib/frename.c
  ADCIRC/thirdparty/metis/Lib/fortran.c
  ADCIRC/thirdparty/metis/Lib/myqsort.c
  ADCIRC/thirdparty/metis/Lib/compress.c
  ADCIRC/thirdparty/metis/Lib/parmetis.c
  ADCIRC/thirdparty/metis/Lib/estmem.c
  ADCIRC/thirdparty/metis/Lib/mpmetis.c
  ADCIRC/thirdparty/metis/Lib/mcoarsen.c
  ADCIRC/thirdparty/metis/Lib/mmatch.c
  ADCIRC/thirdparty/metis/Lib/minitpart.c
  ADCIRC/thirdparty/metis/Lib/mbalance.c
  ADCIRC/thirdparty/metis/Lib/mrefine.c
  ADCIRC/thirdparty/metis/Lib/mutil.c
  ADCIRC/thirdparty/metis/Lib/mfm.c
  ADCIRC/thirdparty/metis/Lib/mkmetis.c
  ADCIRC/thirdparty/metis/Lib/mkwayrefine.c
  ADCIRC/thirdparty/metis/Lib/mkwayfmh.c
  ADCIRC/thirdparty/metis/Lib/mrefine2.c
  ADCIRC/thirdparty/metis/Lib/minitpart2.c
  ADCIRC/thirdparty/metis/Lib/mbalance2.c
  ADCIRC/thirdparty/metis/Lib/mfm2.c
  ADCIRC/thirdparty/metis/Lib/kvmetis.c
  ADCIRC/thirdparty/metis/Lib/kwayvolrefine.c
  ADCIRC/thirdparty/metis/Lib/kwayvolfm.c
  ADCIRC/thirdparty/metis/Lib/subdomains.c)
