list(APPEND _noahmp_files 
  noahmp_ncar/src/AtmosForcingMod.F90
  noahmp_ncar/src/BalanceErrorCheckGlacierMod.F90
  noahmp_ncar/src/BalanceErrorCheckMod.F90
  noahmp_ncar/src/BiochemCropMainMod.F90
  noahmp_ncar/src/BiochemNatureVegMainMod.F90
  noahmp_ncar/src/BiochemVarInitMod.F90
  noahmp_ncar/src/BiochemVarType.F90
  noahmp_ncar/src/CanopyHydrologyMod.F90
  noahmp_ncar/src/CanopyRadiationTwoStreamMod.F90
  noahmp_ncar/src/CanopyWaterInterceptMod.F90
  noahmp_ncar/src/CarbonFluxCropMod.F90
  noahmp_ncar/src/CarbonFluxNatureVegMod.F90
  noahmp_ncar/src/ConfigVarInitMod.F90
  noahmp_ncar/src/ConfigVarType.F90
  noahmp_ncar/src/ConstantDefineMod.F90
  noahmp_ncar/src/CropGrowDegreeDayMod.F90
  noahmp_ncar/src/CropPhotosynthesisMod.F90
  noahmp_ncar/src/EnergyMainGlacierMod.F90
  noahmp_ncar/src/EnergyMainMod.F90
  noahmp_ncar/src/EnergyVarInitMod.F90
  noahmp_ncar/src/EnergyVarType.F90
  noahmp_ncar/src/ForcingVarInitMod.F90
  noahmp_ncar/src/ForcingVarType.F90
  noahmp_ncar/src/GeneralInitGlacierMod.F90
  noahmp_ncar/src/GeneralInitMod.F90
  noahmp_ncar/src/GlacierIceThermalPropertyMod.F90
  noahmp_ncar/src/GlacierPhaseChangeMod.F90
  noahmp_ncar/src/GlacierTemperatureMainMod.F90
  noahmp_ncar/src/GlacierTemperatureSolverMod.F90
  noahmp_ncar/src/GlacierThermalDiffusionMod.F90
  noahmp_ncar/src/GroundAlbedoGlacierMod.F90
  noahmp_ncar/src/GroundAlbedoMod.F90
  noahmp_ncar/src/GroundRoughnessPropertyGlacierMod.F90
  noahmp_ncar/src/GroundRoughnessPropertyMod.F90
  noahmp_ncar/src/GroundThermalPropertyGlacierMod.F90
  noahmp_ncar/src/GroundThermalPropertyMod.F90
  #noahmp_ncar/src/GroundWaterMmfMod.F90
  noahmp_ncar/src/GroundWaterTopModelMod.F90
  noahmp_ncar/src/HumiditySaturationMod.F90
  noahmp_ncar/src/IrrigationFloodMod.F90
  noahmp_ncar/src/IrrigationInfilPhilipMod.F90
  noahmp_ncar/src/IrrigationMicroMod.F90
  noahmp_ncar/src/IrrigationPrepareMod.F90
  noahmp_ncar/src/IrrigationSprinklerMod.F90
  noahmp_ncar/src/IrrigationTriggerMod.F90
  noahmp_ncar/src/Makefile
  noahmp_ncar/src/MatrixSolverTriDiagonalMod.F90
  noahmp_ncar/src/NoahmpMainGlacierMod.F90
  noahmp_ncar/src/NoahmpMainMod.F90
  noahmp_ncar/src/NoahmpVarType.F90
  noahmp_ncar/src/PhenologyMainMod.F90
  noahmp_ncar/src/PrecipitationHeatAdvectGlacierMod.F90
  noahmp_ncar/src/PrecipitationHeatAdvectMod.F90
  noahmp_ncar/src/PsychrometricVariableGlacierMod.F90
  noahmp_ncar/src/PsychrometricVariableMod.F90
  noahmp_ncar/src/ResistanceAboveCanopyChen97Mod.F90
  noahmp_ncar/src/ResistanceAboveCanopyMostMod.F90
  noahmp_ncar/src/ResistanceBareGroundChen97Mod.F90
  noahmp_ncar/src/ResistanceBareGroundMostMod.F90
  noahmp_ncar/src/ResistanceCanopyStomataBallBerryMod.F90
  noahmp_ncar/src/ResistanceCanopyStomataJarvisMod.F90
  noahmp_ncar/src/ResistanceGroundEvaporationGlacierMod.F90
  noahmp_ncar/src/ResistanceGroundEvaporationMod.F90
  noahmp_ncar/src/ResistanceLeafToGroundMod.F90
  noahmp_ncar/src/RunoffSubSurfaceDrainageMod.F90
  noahmp_ncar/src/RunoffSubSurfaceEquiWaterTableMod.F90
  noahmp_ncar/src/RunoffSubSurfaceGroundWaterMod.F90
  noahmp_ncar/src/RunoffSubSurfaceShallowMmfMod.F90
  noahmp_ncar/src/RunoffSurfaceBatsMod.F90
  noahmp_ncar/src/RunoffSurfaceDynamicVicMod.F90
  noahmp_ncar/src/RunoffSurfaceExcessDynamicVicMod.F90
  noahmp_ncar/src/RunoffSurfaceFreeDrainMod.F90
  noahmp_ncar/src/RunoffSurfaceTopModelEquiMod.F90
  noahmp_ncar/src/RunoffSurfaceTopModelGrdMod.F90
  noahmp_ncar/src/RunoffSurfaceTopModelMmfMod.F90
  noahmp_ncar/src/RunoffSurfaceVicMod.F90
  noahmp_ncar/src/RunoffSurfaceXinAnJiangMod.F90
  noahmp_ncar/src/ShallowWaterTableMmfMod.F90
  noahmp_ncar/src/SnowAgingBatsMod.F90
  noahmp_ncar/src/SnowAlbedoBatsMod.F90
  noahmp_ncar/src/SnowAlbedoClassMod.F90
  noahmp_ncar/src/SnowCoverGlacierMod.F90
  noahmp_ncar/src/SnowCoverGroundNiu07Mod.F90
  noahmp_ncar/src/SnowfallBelowCanopyMod.F90
  noahmp_ncar/src/SnowLayerCombineMod.F90
  noahmp_ncar/src/SnowLayerDivideMod.F90
  noahmp_ncar/src/SnowLayerWaterComboMod.F90
  noahmp_ncar/src/SnowpackCompactionMod.F90
  noahmp_ncar/src/SnowpackHydrologyGlacierMod.F90
  noahmp_ncar/src/SnowpackHydrologyMod.F90
  noahmp_ncar/src/SnowThermalPropertyMod.F90
  noahmp_ncar/src/SnowWaterMainGlacierMod.F90
  noahmp_ncar/src/SnowWaterMainMod.F90
  noahmp_ncar/src/SoilHydraulicPropertyMod.F90
  noahmp_ncar/src/SoilMoistureSolverMod.F90
  noahmp_ncar/src/SoilSnowTemperatureMainMod.F90
  noahmp_ncar/src/SoilSnowTemperatureSolverMod.F90
  noahmp_ncar/src/SoilSnowThermalDiffusionMod.F90
  noahmp_ncar/src/SoilSnowWaterPhaseChangeMod.F90
  noahmp_ncar/src/SoilThermalPropertyMod.F90
  noahmp_ncar/src/SoilWaterDiffusionRichardsMod.F90
  noahmp_ncar/src/SoilWaterInfilGreenAmptMod.F90
  noahmp_ncar/src/SoilWaterInfilPhilipMod.F90
  noahmp_ncar/src/SoilWaterInfilSmithParlangeMod.F90
  noahmp_ncar/src/SoilWaterMainMod.F90
  noahmp_ncar/src/SoilWaterSupercoolKoren99Mod.F90
  noahmp_ncar/src/SoilWaterSupercoolNiu06Mod.F90
  noahmp_ncar/src/SoilWaterTranspirationMod.F90
  noahmp_ncar/src/SurfaceAlbedoGlacierMod.F90
  noahmp_ncar/src/SurfaceAlbedoMod.F90
  noahmp_ncar/src/SurfaceEmissivityGlacierMod.F90
  noahmp_ncar/src/SurfaceEmissivityMod.F90
  noahmp_ncar/src/SurfaceEnergyFluxBareGroundMod.F90
  noahmp_ncar/src/SurfaceEnergyFluxGlacierMod.F90
  noahmp_ncar/src/SurfaceEnergyFluxVegetatedMod.F90
  noahmp_ncar/src/SurfaceRadiationGlacierMod.F90
  noahmp_ncar/src/SurfaceRadiationMod.F90
  noahmp_ncar/src/TileDrainageEquiDepthMod.F90
  noahmp_ncar/src/TileDrainageHooghoudtMod.F90
  noahmp_ncar/src/TileDrainageSimpleMod.F90
  noahmp_ncar/src/VaporPressureSaturationMod.F90
  noahmp_ncar/src/WaterMainGlacierMod.F90
  noahmp_ncar/src/WaterMainMod.F90
  noahmp_ncar/src/WaterTableDepthSearchMod.F90
  noahmp_ncar/src/WaterTableEquilibriumMod.F90
  noahmp_ncar/src/WaterVarInitMod.F90
  noahmp_ncar/src/WaterVarType.F90
  noahmp_ncar/utility/CheckNanMod.F90
  noahmp_ncar/utility/ErrorHandleMod.F90
  noahmp_ncar/utility/Machine.F90)

list(APPEND _noahmp_cap_files 
  noahmp_ncar/drivers/nuopc/lnd_comp_domain.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_driver.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_import_export.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_io.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_kind.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_nuopc.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_shr.F90
  noahmp_ncar/drivers/nuopc/lnd_comp_types.F90)
